[package]
name = "po2doc"
version = "0.1.0"
authors = ["ismesunny <lorshousunny@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
